// This file is generated by kconfig_compiler_kf5 from opaSettings.kcfg.
// All changes you do to this file will be lost.

#include "opaSettings.h"

#include <qglobal.h>
#include <QFile>

class opaSettingsHelper
{
  public:
    opaSettingsHelper() : q(nullptr) {}
    ~opaSettingsHelper() { delete q; q = nullptr; }
    opaSettingsHelper(const opaSettingsHelper&) = delete;
    opaSettingsHelper& operator=(const opaSettingsHelper&) = delete;
    opaSettings *q;
};
Q_GLOBAL_STATIC(opaSettingsHelper, s_globalopaSettings)
opaSettings *opaSettings::self()
{
  if (!s_globalopaSettings()->q) {
    new opaSettings;
    s_globalopaSettings()->q->read();
  }

  return s_globalopaSettings()->q;
}

opaSettings::opaSettings( )
  : KConfigSkeleton( QStringLiteral( "oparc" ) )
{
  Q_ASSERT(!s_globalopaSettings()->q);
  s_globalopaSettings()->q = this;
  setCurrentGroup( QStringLiteral( "Preferences" ) );

  KConfigSkeleton::ItemColor  *itemColorBackground;
  itemColorBackground = new KConfigSkeleton::ItemColor( currentGroup(), QStringLiteral( "colorBackground" ), mColorBackground, QColor( "black" ) );
  addItem( itemColorBackground, QStringLiteral( "colorBackground" ) );
  KConfigSkeleton::ItemColor  *itemColorForeground;
  itemColorForeground = new KConfigSkeleton::ItemColor( currentGroup(), QStringLiteral( "colorForeground" ), mColorForeground, QColor( "yellow" ) );
  addItem( itemColorForeground, QStringLiteral( "colorForeground" ) );
  KConfigSkeleton::ItemInt  *itemAgeInDays;
  itemAgeInDays = new KConfigSkeleton::ItemInt( currentGroup(), QStringLiteral( "ageInDays" ), mAgeInDays, 2 );
  addItem( itemAgeInDays, QStringLiteral( "ageInDays" ) );
}

opaSettings::~opaSettings()
{
  if (s_globalopaSettings.exists() && !s_globalopaSettings.isDestroyed()) {
    s_globalopaSettings()->q = nullptr;
  }
}

