name: Build project

on:
  pull_request:
  push:

jobs:
  build:
    name: build targets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/flake-checker-action@v9
      - uses: nixbuild/nix-quick-install-action@v29
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build
